# Generated by Django 2.2.4 on 2020-12-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderIteams',
            new_name='orderItems',
        ),
    ]
